{% set name = "streamlit-condition-tree" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cedricvlt/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5895a9c0546cf5facc9db0f84d76310403c22da291c99ec0519235d12c5e480b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - streamlit >=0.63

test:
  imports:
    - streamlit_condition_tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cedricvlt/streamlit-condition-tree
  dev_url: https://github.com/cedricvlt/streamlit-condition-tree
  doc_url: https://github.com/cedricvlt/streamlit-condition-tree/blob/master/README.md
  summary: A Streamlit component to build a condition tree
  description: |
    This component allows users to build complex condition trees that can be used to filter a dataframe or build a query.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - psteyer
